name: privtatize_ai
description: "A customizable white-label Flutter application for enterprises, powered by Azure ChatGPT Client, designed for easy adaptation and use."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.6 
  http: ^0.13.3
  flutter_secure_storage: ^5.0.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.6
  pointycastle: ^3.7.4
  event_bus: ^2.0.0
  url_launcher: ^6.2.5
  flutter_gen: ^4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  generate: true

flutter_icons:
  android: true 
  ios: true
  image_path: "icon/icon.png"
